# -*- coding: utf-8 -*-
"""
Plagiarism Detection Module - Content similarity and AI detection
"""
import os
import math
import logging
from collections import Counter

logger = logging.getLogger(__name__)


def check_plagiarism(essay_text, candidate_id):
    """
    Check for plagiarism and AI-generated content.
    
    Returns:
        dict with similarity_score, ai_probability, flagged status
    """
    from app.models.exam import WritingAnswer
    
    result = {
        'similarity_score': 0.0,
        'similar_to_id': None,
        'ai_generated_probability': 0.0,
        'flagged': False,
        'flag_reasons': []
    }
    
    # Get other writing answers for comparison
    other_answers = WritingAnswer.query.filter(
        WritingAnswer.aday_id != candidate_id,
        WritingAnswer.essay_text.isnot(None)
    ).limit(100).all()
    
    max_similarity = 0
    most_similar_id = None
    
    for answer in other_answers:
        if answer.essay_text:
            similarity = cosine_similarity_text(essay_text, answer.essay_text)
            if similarity > max_similarity:
                max_similarity = similarity
                most_similar_id = answer.id
    
    result['similarity_score'] = round(max_similarity * 100, 1)
    result['similar_to_id'] = most_similar_id
    
    # Check for AI-generated content
    ai_prob = check_ai_generated(essay_text)
    result['ai_generated_probability'] = ai_prob
    
    # Determine if flagged
    if max_similarity > 0.75:
        result['flagged'] = True
        result['flag_reasons'].append(f'Yüksek benzerlik: %{result["similarity_score"]}')
    
    if ai_prob > 0.7:
        result['flagged'] = True
        result['flag_reasons'].append(f'AI tarafından yazılmış olabilir: %{round(ai_prob * 100)}')
    
    return result


def cosine_similarity_text(text1, text2):
    """Calculate cosine similarity between two texts."""
    # Tokenize and create word frequency vectors
    words1 = text1.lower().split()
    words2 = text2.lower().split()
    
    vec1 = Counter(words1)
    vec2 = Counter(words2)
    
    # Get all unique words
    all_words = set(vec1.keys()) | set(vec2.keys())
    
    # Calculate dot product and magnitudes
    dot_product = sum(vec1.get(w, 0) * vec2.get(w, 0) for w in all_words)
    mag1 = math.sqrt(sum(v ** 2 for v in vec1.values()))
    mag2 = math.sqrt(sum(v ** 2 for v in vec2.values()))
    
    if mag1 == 0 or mag2 == 0:
        return 0.0
    
    return dot_product / (mag1 * mag2)


def check_ai_generated(text):
    """
    Check if text was likely generated by AI.
    Uses Gemini to analyze writing patterns.
    """
    api_key = os.getenv('GEMINI_API_KEY')
    if not api_key:
        return 0.0
    
    try:
        import google.generativeai as genai
        
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel('gemini-pro')
        
        prompt = f"""Analyze this essay and determine the probability (0.0 to 1.0) that it was written by an AI.

Consider these factors:
- Unusual consistency in sentence structure
- Lack of personal voice or opinions  
- Perfect grammar throughout
- Generic or template-like responses
- Repetitive phrase patterns

TEXT:
{text[:2000]}

Return ONLY a number between 0.0 and 1.0, nothing else."""

        response = model.generate_content(prompt)
        prob = float(response.text.strip())
        return max(0.0, min(1.0, prob))
        
    except Exception as e:
        logger.error(f"AI detection failed: {e}")
        return 0.0
